[build]	
    base    = "docs"
    publish = "_site"
    command = "npm build"
    build = "build"

[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"